import './globals.css';
import React from 'react';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { LogoutButton } from '@/app/_components/LogoutButton';
import { LoginButton } from '@/app/_components/LoginButton';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`min-h-screen ${geistSans.variable} ${geistMono.variable}`}>
        <div className="grid h-screen grid-rows-[50px_auto] gap-2">
          <header className="grid content-center border-2 border-white p-4">
            <div className="flex justify-between">
              <LoginButton />
              <LogoutButton />
            </div>
          </header>
          <div className="grid content-center justify-center border-2 border-white">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
